sudo: required
services:
  - docker

before_install:
  - docker build -t sebastianulbrich/docker-react -f Dockerfile.dev .

script:
  - docker run sebastianulbrich/docker-react npm run test -- --coverage