sudo: required
language: generic 
services:
  - sample-docker-react

before_install:
  - docker build -t sebastianulbrich/sample-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sebastianulbrich/sample-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "sample-docker-react"
  env: "SampleDockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-712768071943"
  bucket_path: "sample-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY